"""
Test Documentation Generator Integration
"""
import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import json
sys.path.append(os.getcwd())

from app.services.spec_utils import create_initial_spec
from app.services.doc_generator import generate_project_documentation

def test_doc_generation():
    print("\n🚀 Starting Documentation Generator Test")
    print("=" * 60)
    
    # 1. Create a mock spec
    spec = create_initial_spec("test-proj-123", "A social network for cats")
    print(f"✓ Created Mock Spec: {spec.project.name}")
    
    # 2. Generate Documentation
    doc = generate_project_documentation(spec)
    print("✓ Documentation Generated")
    
    # 3. Verify Content
    print("\n--- Preview ---")
    print(doc[:500] + "...\n")
    
    # Check sections exist
    assert "## 1. Executive Summary" in doc
    assert "## 2. Requirements" in doc
    assert "## 3. Architecture" in doc
    
    # Check Logic
    assert spec.project.purpose in doc
    assert f"System Archetype**: {spec.architecture.archetype.value}" in doc
    assert "*Generated by Alchemy*" in doc
    
    print("✅ Documentation Test Passed!")

if __name__ == "__main__":
    try:
        test_doc_generation()
    except Exception as e:
        print(f"\n❌ Test Failed: {e}")
